# ModbusMQTTBridge Configuration
# config.yaml

# Modbus Connection Settings
modbus:
  host: "192.168.1.100"  # IP address of the Modbus device
  port: 502              # Default Modbus TCP port
  unit_id: 1             # Modbus unit/slave ID
  timeout: 5             # Connection timeout in seconds
  retries: 3             # Number of connection retry attempts
  retry_delay: 2         # Delay between retries in seconds

# MQTT Connection Settings
mqtt:
  broker: "35.169.3.101" 
  port: 1884             
  topic: "device/modbus" 
  qos: 1                 
  retain: false          
  client_id: "modbus-bridge-1"
  username: "mqtt_user"  
  password: "mqtt_pass"  
  tls: false             

# Register Definitions - Only include registers that actually exist on server
registers:
  # Temperature sensor at register 40001
  - name: "Temperature"
    address: 40001
    count: 1
    scale: 0.1
    unit: "°C"
    data_type: "int16"
    byte_order: "big"
  
  # Voltage measurement at register 40002
  - name: "Voltage"
    address: 40002
    count: 1
    scale: 0.01
    unit: "V"
    data_type: "int16"
    byte_order: "big"
  
  # Power measurement (32-bit value across two registers)
  - name: "Power"
    address: 40003
    count: 2
    scale: 0.001
    unit: "kW"
    data_type: "int32"
    byte_order: "big"

# Application Settings
loop_interval: 10          
reconnect_interval: 30     
health_check_interval: 60  
json_file: "modbus_data.json"